//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_radnih_sati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evidencija_radnih_sati.Resources.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekovremeni sati moraju biti u rasponu 0-4.
        /// </summary>
        public static string PrekovremeniSati {
            get {
                return ResourceManager.GetString("PrekovremeniSati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekovremeni sati ukupno moraju biti u rasponu 0-4.
        /// </summary>
        public static string PrekovremeniSatiUkupno {
            get {
                return ResourceManager.GetString("PrekovremeniSatiUkupno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radni sati moraju biti u rasponu 0-8.
        /// </summary>
        public static string RadniSati {
            get {
                return ResourceManager.GetString("RadniSati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radni sati ukupno moraju biti 8.
        /// </summary>
        public static string RadniSatiUkupno {
            get {
                return ResourceManager.GetString("RadniSatiUkupno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaporka ne može biti prazna.
        /// </summary>
        public static string ZaporkaPrazna {
            get {
                return ResourceManager.GetString("ZaporkaPrazna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaporka ne može sadržavati posebne znakove i mora biti duljine između 3 i 20 znakova.
        /// </summary>
        public static string ZaporkaRegex {
            get {
                return ResourceManager.GetString("ZaporkaRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaporke nisu jednake.
        /// </summary>
        public static string ZaporkeNisuJednake {
            get {
                return ResourceManager.GetString("ZaporkeNisuJednake", resourceCulture);
            }
        }
    }
}
