//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_radnih_sati.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profil() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evidencija_radnih_sati.Resources.Profil", typeof(Profil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zaposlenja.
        /// </summary>
        public static string DatumZaposlenja {
            get {
                return ResourceManager.GetString("DatumZaposlenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova zaporka.
        /// </summary>
        public static string NovaZaporka {
            get {
                return ResourceManager.GetString("NovaZaporka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovite novu zaporku.
        /// </summary>
        public static string PonoviteNovuZaporku {
            get {
                return ResourceManager.GetString("PonoviteNovuZaporku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string ProfilNaslov {
            get {
                return ResourceManager.GetString("ProfilNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena zaporke.
        /// </summary>
        public static string PromjenaZaporke {
            get {
                return ResourceManager.GetString("PromjenaZaporke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjeni zaporku.
        /// </summary>
        public static string PromjeniZaporku {
            get {
                return ResourceManager.GetString("PromjeniZaporku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string Spremi {
            get {
                return ResourceManager.GetString("Spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip djelatnika.
        /// </summary>
        public static string TipDjelatnika {
            get {
                return ResourceManager.GetString("TipDjelatnika", resourceCulture);
            }
        }
    }
}
